### ISSUE TITLE
Reading once

### ISSUE THREAD

**Issue by J-A-U** [mysmartgrid/vzlogger#4]
Older versions of vzlogger read an sml-type-meter only once and quit when called without the -d option.
Actually the vzlogger is reading permanent. With or without -d or deamon:true|false;.

Problem: A sml-meter with output every second generates masses of data. I tried to reduce the data by calling vzlogger as cronjob. Unstable, but principally working for older (c) version.

Actually impossible with the c++-Version.

**Comment by peterevertz** [comment]
I have just implented the aggregation in c++ vzlogger. 
Feel free to test. 
Contains some bugfixes and more which should be fixed here also. ( e.g. broken Buffer::clean() )

https://github.com/peterevertz/vzlogger.git ( fork of https://github.com/volkszaehler/vzlogger )
